services:
  webapi:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      - .:/app
    command: dotnet watch run
    depends_on:
      - pgsql
    networks:
      - teste-tecnico

  pgsql:
    image: postgres:16-bullseye
    container_name: pgsql
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - teste-tecnico

networks:
  teste-tecnico:
    driver: bridge
