services:
  frontend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm start
    container_name: angular-dev
